version: "3.9"

services:
  manager:
    build: .
    image: honeygain_manager
    container_name: honeygain_manager
    volumes:
      - ../configs:/app/configs
      - hg-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env

volumes:
  hg-data:
